module.exports = {
    rules: {
        'array-callback-return': 2,
        'array-bracket-spacing': 2,
        'arrow-spacing': 2,
        'block-scoped-var': 2,
        'block-spacing': 2,
        'brace-style': 2,
        'comma-dangle': [2, 'always-multiline'],
        'comma-spacing': 2,
        'comma-style': 2,
        'constructor-super': 2,
        curly: 2,
        'dot-notation': 2,
        'func-call-spacing': 2,
        'jsx-quotes': 2,
        'key-spacing': 2,
        'keyword-spacing': 2,
        'linebreak-style': [2, 'unix'],
        'object-curly-spacing': [2, 'always', { arraysInObjects: false }],
        'operator-linebreak': 2,
        'prefer-arrow-callback': 2,
        'prefer-spread': 2,
        'mocha/no-exclusive-tests': 'error',
        'no-case-declarations': 0,
        'no-console': 0,
        'no-dupe-class-members': 2,
        'no-duplicate-imports': 2,
        'no-empty-pattern': 2,
        'no-multiple-empty-lines': 2,
        'no-nested-ternary': 2,
        'no-spaced-func': 2,
        'no-this-before-super': 2,
        'no-trailing-spaces': 2,
        'no-unsafe-negation': 2,
        'no-unused-vars': [2, { vars: 'all', args: 'none' }],
        'no-useless-computed-key': 2,
        'no-useless-constructor': 2,
        'no-whitespace-before-property': 2,
        quotes: [2, 'single', 'avoid-escape'],
        semi: [2, 'always'],
        'space-before-blocks': 2,
        'jsx-a11y/alt-text': 2,
        'jsx-a11y/img-redundant-alt': 2,
        'prettier/prettier': [
            'error',
            {
                singleQuote: true,
                trailingComma: 'all',
                jsxBracketSameLine: true,
                printWidth: 160,
                tabWidth: 4,
            },
        ],
        'react/jsx-boolean-value': [2, 'always'],
        'react/jsx-closing-bracket-location': [2, { selfClosing: 'tag-aligned', nonEmpty: 'after-props' }],
        'react/jsx-curly-spacing': 2,
        'react/jsx-equals-spacing': 2,
        'react/jsx-key': 2,
        'react/jsx-no-duplicate-props': 2,
        'react/jsx-no-undef': 2,
        'react/jsx-pascal-case': [2, { allowAllCaps: true }],
        'react/jsx-tag-spacing': 2,
        'react/jsx-uses-react': 2,
        'react/jsx-uses-vars': 2,
        'react/no-children-prop': 2,
        'react/no-deprecated': 2,
        'react/no-did-update-set-state': 2,
        'react/no-direct-mutation-state': 2,
        'react/no-string-refs': 2,
        'react/no-unknown-property': 2,
        'react/no-unused-prop-types': 2,
        'react/react-in-jsx-scope': 2,
        'react/require-render-return': 2,
        'react/self-closing-comp': 2,
    },
    env: {
        es6: true,
        commonjs: true,
        browser: true,
        node: true,
        jest: true,
        mocha: true,
    },
    extends: ['eslint:recommended', 'plugin:react/recommended'],
    parser: 'babel-eslint',
    parserOptions: {
        sourceType: 'module',
        ecmaFeatures: {
            jsx: true,
            experimentalObjectRestSpread: true,
        },
    },
    globals: {
        Intercom: false,
        BROWSER: false,
        SKIP_SLOW_TESTS: false,
        LogRocket: false,
        mapboxgl: false,
        GRAPHQLURL: false,
    },
    plugins: ['react', 'jsx-a11y', 'mocha', 'prettier'],
};
